trigger:
- '*'  

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build NestJS app'

- script: |
    npm install --save-dev jest-junit
    npx jest --ci --reporters=default --reporters=jest-junit
  displayName: 'Run unit tests with JUnit report'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/junit.xml'
    testResultsFormat: 'JUnit'
  condition: succeededOrFailed()
  displayName: 'Publish test results'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'nestjs-app'
    publishLocation: 'Container'
  displayName: 'Publish build artifact'
